name: Build and Publish Docker Image
on:
  push:
    branches: [ main ]
    tags: [ 'v*', 'release-*' ]

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare tags
        id: prep
        run: |
          OWNER_LC="${GITHUB_REPOSITORY_OWNER,,}"
          IMAGE="ghcr.io/${OWNER_LC}/cursor-free-vip"
          echo "image=${IMAGE}" >> $GITHUB_OUTPUT
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            VERSION="${GITHUB_REF_NAME}"
          else
            VERSION="sha-${GITHUB_SHA::7}"
          fi
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          provenance: false
          platforms: linux/amd64,linux/arm64
          build-args: |
            WITH_BROWSER=true
          tags: |
            ${{ steps.prep.outputs.image }}:${{ steps.prep.outputs.version }}
            ${{ steps.prep.outputs.image }}:latest